services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-main
    ports:
      - "8000:8000"
#    expose:
#      - "8000"
    environment:
      - PYTHONPATH=.
    env_file:
      - .env
    volumes:
      - ".:/app"
      - "./static:/app/static"
    restart: always

